version:  '3'
services:
  ytview:
    build:
      context: .
    image: youtube-viewer/ytview
    restart: unless-stopped
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
