#!/usr/bin/env node

'use strict'

require('./dist/cli');
/**
const Application = require('@viewer/core/application')

// https://github.com/orassayag/spam-revenge

/**
 * Kick off the command line helper called "youtube-viewer". Youtube-viewer commands
 * can scaffold features or project files. The CLI command will
 * execute in the terminal and terminate itself once finished.
 *\/
new Application()
    .fromAppRoot(__dirname)
    .consoleForLife()
 */
