export const Selectors = {
    pageBody: 'body',
    iframe: 'iframe',
    gdprButton: 'button[aria-label^="Agree"]',
    introAgreeButton: '#introAgreeButton',
    playButton: 'button[aria-label="Play (k)"]',
    // playButton: '#movie_player > div.ytp-chrome-bottom > div.ytp-chrome-controls > div.ytp-left-controls > button[aria-label="Play (k)"]',
    closeCookie: 'button[jsname="higCR"]',
    noThanksButton: '#button[aria-label="No thanks"]',
    dismissBullshitButton: '#dismiss-button paper-button',
    consentIframe: 'iframe[src*="consent"]',
    consentForm: 'form[action*="consent"]',
    skipAdButton: 'button[class*="skip-button"]',
    playerView: 'div[id="player-container-inner]',
    searchBar: 'input[id="search"]',
    identifierId: '#identifierId',
    identifierNext: '#identifierNext',
    accountDetailsNext: '#accountDetailsNext',
    createAnAccount: '.VfPpkd-xl07Ob-XxIAqe-OWXEXe-oYxtQd > div > .VfPpkd-dgl2Hf-ppHlrf-sM5MNb > .VfPpkd-LgbsSe > .VfPpkd-vQzf8d',
    clickForMe: '.VfPpkd-xl07Ob-XxIAqe-OWXEXe-oYxtQd > div > .VfPpkd-xl07Ob-XxIAqe > .VfPpkd-StrnGf-rymPhb > .G3hhxb:nth-child(2)',
    clickCreateNewEmail: 'div > .ltfTcc > .VfPpkd-dgl2Hf-ppHlrf-sM5MNb > .VfPpkd-LgbsSe > .VfPpkd-vQzf8d',
    videoRenderer: 'ytd-video-renderer,ytd-grid-video-renderer',
    register: '#view_container > div > div > div.pwWryf.bxPAYd > div > div.zQJV3 > div > div.daaWTb > div > div > div:nth-child(1) > div > button > span',
    firstName: 'input[type="text"][name="firstName"]', // #firstName
    lastName: 'input[type="text"][name="lastName"]', // #lastName
    username: 'input[type="email"]',
    password: 'input[type="password"][name="Passwd"]',
    confirmPasswd: 'input[type="password"][name="ConfirmPasswd"]',
    submit: 'button[class="VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc qIypjc TrZEUc lw1w4b"]',
    phoneNumber: 'input[type="tel"]',
    recoveryEmail: 'input[type="email"][name="recoveryEmail"]',
    phoneNext: '#view_container > div > div > div.pwWryf.bxPAYd > div > div.zQJV3 > div > div.qhFLie > div > div > button > div.VfPpkd-RLmnJb',
    verifyCode: 'input[type="tel"][name="code"]',
    acceptConditions: 'button[type="button"][jsname="LgbsSe"]',
    day: 'input[name="day"]',
    month: '#month',
    year: 'input[name="year"]',
};
export const _clicked = {};
