'use strict'

const services = [
    { service: 'Google' },
    { service: 'Facebook' },
    { service: 'WhatsApp' },
    { service: 'LINE' },
    { service: 'Chatroulette' },
    { service: 'eBay' },
    { service: 'Instagram' },
    { service: 'BeeTalk' },
    { service: 'Telegram' },
    { service: 'Yahoo' },
    { service: 'VK.com Vkontakte English' },
    { service: 'Naver' },
    { service: 'Airbnb' },
    { service: 'freelancer' },
    { service: 'Webmoney' },
    { service: 'Tinder' },
    { service: 'Viber' },
    { service: 'Twitter (English)' },
    { service: '.com' },
    { service: 'Azure' },
    { service: 'skype' },
    { service: 'Baidu' },
    { service: 'Uber' },
    { service: 'Astrill' },
    { service: 'Amazon' },
    { service: 'ICQ' },
    { service: 'APP.net' },
    { service: 'TALK' },
    { service: 'Vine' },
    { service: 'KakaoTalk' },
    { service: 'Twilio' },
    { service: 'Badoo' },
    { service: 'snapchat' },
    { service: 'Weebly' },
    { service: 'OKru' },
    { service: ' Cloud' },
    { service: 'Microsoft' },
    { service: 'Nvidia' },
    { service: 'SmartCall' },
    { service: 'MeetMe' },
    { service: 'PCGameSupply' },
    { service: 'Yandex.com' },
    { service: 'Vonage' },
    { service: 'GrabTaxi' },
    { service: 'Careem' },
    { service: 'NETEASE - ' },
    { service: 'Sina Mail' },
    { service: 'BitGold' },
    { service: 'Fiverr' },
    { service: 'AOL' },
    { service: 'Playtoken(Chinese)' },
    { service: 'IMO' },
    { service: 'Baofeng Mojing' },
    { service: 'MOLO' },
    { service: 'Getresponse' },
    { service: 'Coins.ph' },
    { service: 'localbitcoins' },
    { service: 'Anyan' },
    { service: 'Weibo' },
    { service: 'ctyun' },
    { service: 'Turecaller' },
    { service: 'mhao.com' },
    { service: 'iSharkey' },
    { service: 'FreeBitco.in' },
    { service: 'Ticwatch' },
    { service: 'Baihe/百合网' },
    { service: 'Zhenai' },
    { service: 'Jiayuan' },
    { service: 'Coinbase' },
    { service: 'Circle' },
    { service: 'Mytaxi' },
    { service: 'EZVIZ - Chinese version' },
    { service: 'Tuandai' },
    { service: '少女前线' },
    { service: 'BAND.us' },
    { service: 'Zhenfu' },
    { service: 'dabtc' },
    { service: 'Alibaba' },
    { service: 'Carousell' },
    { service: 'Xiaomi' },
    { service: 'Lyft' },
    { service: 'zhgtrade.com' },
    { service: 'Youku' },
    { service: 'Bileyuan|币乐园' },
    { service: 'mmbang|妈妈帮' },
    { service: 'fetlife' },
    { service: 'Ninebot' },
    { service: 'IT' },
    { service: 'Gameflip' },
    { service: 'Goluk' },
    { service: 'QQ' },
    { service: 'skout' },
    { service: 'SEAGM' },
    { service: 'Yuanbao' },
    { service: 'Protonmail' },
    { service: 'VENMO' },
    { service: '.com' },
    { service: 'Wirex' },
    { service: 'Gett' },
    { service: 'jubi.com' },
    { service: 'zbj.com' },
    { service: 'yobtc' },
    { service: 'IT Pro Cloud' },
    { service: 'Wechat(Test before use)' },
    { service: 'Laohu.com' },
    { service: 'Epay' },
    { service: 'Bidvertiser' },
    { service: 'Panda.tv' },
    { service: 'Badoo Regsiter' },
    { service: 'w.com' },
    { service: 'Listia' },
    { service: 'Steam' },
    { service: 'Skout' },
    { service: 'Purse.io' },
    { service: 'Uber English' },
    { service: 'Daum' },
    { service: 'Goldmoney' },
    { service: '酷划|Coohua' },
    { service: 'Rebtel' },
    { service: 'NobelApp' },
    { service: 'Mailgun' },
    { service: 'Stage动漫游戏社区' },
    { service: 'Yandex.ru' },
    { service: '鑫币网|xinbi.com' },
    { service: 'stellar' },
    { service: 'Huawei Wear' },
    { service: 'BTC' },
    { service: 'Qiniu|七牛云' },
    { service: 'TCL|铁粉' },
    { service: 'zhiji|知己网' },
    { service: 'Letv|乐视' },
    { service: 'Flexiroam X' },
    { service: 'Advcash' },
    { service: 'Vipkid.com.cn' },
    { service: 'MTCGMAE' },
    { service: 'Hotcast.cn' },
    { service: 'Mymusictaste' },
    { service: 'Periscope' },
    { service: 'Lecheng' },
    { service: 'Youzu|游族' },
    { service: 'niu.com|小牛电动' },
    { service: 'uCoz' },
    { service: 'Nttgame' },
    { service: 'digits' },
    { service: 'Colu' },
    { service: 'Nike' },
    { service: 'chedingdong|车叮咚' },
    { service: 'Ximalaya|喜马拉雅电台' },
    { service: 'Zhekou|昭诚' },
    { service: 'Fastmail' },
    { service: 'MapleStory|冒险岛' },
    { service: 'Uber eats' },
    { service: 'Craigslist(For USA)' },
    { service: 'Leupay' },
    { service: '星城online' },
    { service: 'Content.ad' },
    { service: 'FL.ru' },
    { service: '易介|yijie' },
    { service: 'Zoho' },
    { service: 'GA' },
    { service: 'Epay' },
    { service: 'hwcloud|华为云' },
    { service: 'UR money' },
    { service: 'BuySomeBitcoins' },
    { service: 'job' },
    { service: 'Ninebot APP' },
    { service: 'RichmondBerks' },
    { service: 'Wire' },
    { service: 'flippa' },
    { service: 'ZoomInfo' },
    { service: 'Perfect World|完美世界' },
    { service: 'Mail.ru' },
    { service: 'PlayerAuctions' },
    { service: 'steemit' },
    { service: 'Affirm' },
    { service: 'Shopee' },
    { service: 'Oracle' },
    { service: 'zhan.com|小站' },
    { service: 'Zoosk' },
    { service: 'zen.ly' },
    { service: 'Bitekuang|比特矿' },
    { service: 'yes.com.tw' },
    { service: 'Humblebundle' },
    { service: 'Musical.ly' },
    { service: '比特币交易网|btctrade.com' },
    { service: 'gatehub.net' },
    { service: 'Comfi' },
    { service: 'UnitedStack' },
    { service: 'foodpanda' },
    { service: 'ICOAGE' },
    { service: 'luno' },
    { service: 'Linkedin' },
    { service: 'callfriends' },
    { service: 'Shasso' },
    { service: 'OffGamers' },
    { service: 'Okpay' },
    { service: 'Streetbees' },
    { service: 'Office ' },
    { service: 'foodora' },
    { service: 'thaifriendly' },
    { service: 'paxful' },
    { service: 'Primo' },
    { service: '音悦Tai|yinyuetai' },
    { service: 'YY.com' },
    { service: 'Cdkeys.com' },
    { service: 'CSDN.net' },
    { service: 'zhihu.com' },
    { service: '果盘游戏' },
    { service: 'Honestbee' },
    { service: 'Jiaoyou|中国交友网' },
    { service: 'GamaniaHK' },
    { service: '币久|BTC' },
    { service: 'Livescore' },
    { service: 'ico' },
    { service: 'ico' },
    { service: 'beico.io' },
    { service: 'Xunlei|迅雷' },
    { service: 'allcoin' },
    { service: '微软小冰' },
    { service: 'JD register|京东注册' },
    { service: 'btc.com' },
    { service: '见见|jianjian' },
    { service: '有缘|youyuan' },
    { service: '缘分|yf.com' },
    { service: 'CheckPoints' },
    { service: 'simwe.com' },
    { service: 'Discord' },
    { service: 'Spotify' },
    { service: '慧博|hibor.com.cn' },
    { service: '巨人网络|ztgame.com' },
    { service: 'adidas' },
    { service: 'gfan.com' },
    { service: 'FAVE' },
    { service: 'Klook' },
    { service: 'VK.com Russia' },
    { service: 'Tiancity世纪天成' },
    { service: 'huomao|火猫' },
    { service: 'Authy' },
    { service: 'Ankama' },
    { service: 'Sonetel' },
    { service: 'Vmall|华为商城' },
    { service: 'Telz' },
    { service: 'zadarma' },
    { service: 'zalo.me' },
    { service: 'wacoin.io' },
    { service: 'travelmob' },
    { service: 'Signal.org' },
    { service: 'Bitmain比特大陆' },
    { service: 'mai|迈' },
    { service: 'backpage' },
    { service: 'eefocus|与非网' },
    { service: 'HC|慧聪网' },
    { service: 'yhd.com|一号店' },
    { service: 'Backblaze' },
    { service: 'Meme Live APP|么么直播' },
    { service: 'Bussinessstore Mircosoft' },
    { service: 'avis.cn' },
    { service: '.com' },
    { service: 'xcoins' },
    { service: 'coinmeet' },
    { service: 'SEMrush' },
    { service: 'xiangcloud象云' },
    { service: 'binance币安' },
    { service: 'Hushmail' },
    { service: 'LBANK.INFO' },
    { service: 'ymatou|洋码头' },
    { service: 'Kuaishou|快手' },
    { service: 'Huobi|火币' },
    { service: 'HQ trivia' },
    { service: 'wotb..com' },
    { service: 'moab.pro' },
    { service: 'coinw' },
    { service: '中信楷岚' },
    { service: 'LOVESTRUCK' },
    { service: 'Tantan|探探' },
    { service: 'Momo|陌陌' },
    { service: 'paktor' },
    { service: 'CenturyLink' },
    { service: '绝地求生' },
    { service: 'HB.TOP' },
    { service: 'Oracle' },
    { service: 'DateInAsia' },
    { service: 'ClickGem' },
    { service: 'DoorDash' },
    { service: 'Cash Show' },
    { service: 'Luna Node' },
    { service: 'z.com' },
    { service: 'coinbene' },
    { service: 'LBRY' },
    { service: 'Juno' },
    { service: 'Sohu' },
    { service: 'ooopic' },
    { service: 'JapanCodeSupply' },
    { service: 'dyson' },
    { service: 'douyin' },
    { service: 'douban' },
    { service: 'cgame' },
    { service: 'Rediffmail' },
    { service: 'Hupu|虎扑' },
    { service: 'dukascopy' },
    { service: '露天拍賣' },
    { service: 'izhenxin爱真心' },
    { service: '蜗壳woker.cc' },
    { service: 'netflix' },
    { service: 'Revolut' },
    { service: 'electroneum' },
    { service: 'vivo' },
    { service: 'BIXIN比心' },
    { service: 'Telegram(New SIM)' },
    { service: 'Nike(New SIM)' },
    { service: 'Soroush' },
    { service: 'GG大玩家' },
    { service: 'LeaseVille' },
    { service: 'Nate' },
    { service: 'btok' },
    { service: 'Viberate' },
    { service: 'ClassPass' },
    { service: 'Duowan' },
    { service: 'GOFUNDME' },
    { service: 'oneplus|一加手机' },
    { service: 'CTRIP|携程' },
    { service: 'MUSDcoin' },
    { service: 'Sweatcoin' },
    { service: 'Sendgrid' },
    { service: 'Apple' },
    { service: 'epnex' },
    { service: 'Bumble' },
    { service: 'FacePoker' },
    { service: '部落先锋' },
    { service: '扑克王' },
    { service: '超级扑克' },
    { service: '王国游戏' },
    { service: '智玩竞技' },
    { service: 'Oh Poker' },
    { service: '触宝电话' },
    { service: '宝二爷令牌' },
    { service: 'Messenger' },
    { service: 'Razer Pay' },
    { service: 'Scaleway' },
    { service: 'OPPO' },
    { service: 'ylike|缘来客' },
    { service: 'hongniang|中国红娘' },
    { service: 'phicomm' }
]

export const countryCodes: Map<string, number> = new Map([
    ['russia', 7],
    ['ukraine', 380],
    ['germany', 49],
    ['united kingdom', 49],
    ['france', 33],
    ['spain', 34],
    ['sweden ', 46],
    ['netherlands', 31],
    ['denmark', 45],
    ['cyprus', 357],
    ['usa', 1],
    ['austria', 43],
    ['czech', 420],
    ['poland', 48],
    ['romania ', 40],
    ['haiti', 509],
    ['morocco', 212],
    ['indonesia', 62],
    ['philippines', 63],
    ['vietnam', 84],
    ['latvia', 371],
    ['lithuania', 370],
    ['estonia', 372],
    ['serbia', 381],
    ['moldova', 373],
    ['georgia', 995],
    ['kirghizia', 996],
    ['kazakhstan', 77],
    ['brasil', 55],
    ['mexico', 52],
    ['argentina', 54],
    ['turkey', 90],
    ['egypt', 20],
    ['israel', 972],
    ['india', 91],
    ['yemen', 967],
    ['hongkong', 852],
    ['nigeria', 234],
    ['ivory', 225],
    ['uzbekistan', 998],
    ['ghana', 233],
    ['bulgaria', 359],
    ['kenya', 254],
    ['colombia', 57],
    ['honduras', 504],
    ['pakistan', 92],
    ['burkinafaso', 226],
    ['iraq', 964],
    ['azerbaijan', 994],
    ['iran', 98],
    ['bolivia', 591],
    ['srilanka', 94],
    ['mongolia', 976],
    ['mali', 223],
    ['nepal', 977],
    ['chad', 235],
    ['guinea', 224],
    ['liberia', 231],
    ['sierraleone', 232],
    ['china', 86],
    ['cameroon', 237],
    ['croatia', 385],
    ['tanzania', 255],
    ['venezuela', 58],
    ['taiwan', 886],
    ['malaysia', 60],
    ['gambia', 220],
    ['belgium', 32],
    ['аlgeria', 213],
    ['australia', 61],
    ['norway', 47],
    ['belorussia', 375],
    ['portugal', 351],
    ['tajikistan', 992],
    ['afghanistan', 93],
    ['ireland', 353],
    ['finland', 358],
    ['italy', 39]
]);

const countriesCodes = new Set([
    7,	    // russia
    380,	// ukraine
    49,	    // germany
    44,	    // united_kingdom
    33,	    // france
    34,	    // spain
    46,	    // sweden
    31,	    // netherlands
    45,	    // denmark
    357,	// cyprus
    1000,	// canada
    1,	    // usa
    43,	    // austria
    420,	// czech
    48,	    // poland
    40,	    // romania
    509,	// haiti
    212,    // morocco
    62,	    // indonesia
    63,	    // philippines
    84,	    // vietnam
    371,	// latvia
    370,	// lithuania
    372,	// estonia
    381,	// serbia
    373,	// moldova
    995,	// georgia
    996,	// kirghizia
    77,	    // kazakhstan
    55,	    // brasil
    52,	    // mexico
    54,	    // argentina
    90,	    // turkey
    20,	    // egypt
    972,	// israel
    91,	    // india
    967,	// yemen
    852,	// hongkong
    234,	// nigeria
    225,	// ivory
    998,	// uzbekistan
    233,	// ghana
    359,	// bulgaria
    254,	// kenya
    57,	    // colombia
    504,	// honduras
    92,	    // pakistan
    226,	// burkinafaso
    964,	// iraq
    994,	// azerbaijan
    98,	    // iran
    591,	// bolivia
    94,	    // srilanka
    976,	// mongolia
    223,	// mali
    977,	// nepal
    235,	// chad
    224,	// guinea
    231,	// liberia
    232,	// sierraleone
    86,	    // china
    237,	// cameroon
    385,	// croatia
    255,	// tanzania
    58,	    // venezuela
    886,	// taiwan
    60,	    // malaysia
    220,	// gambia
    32,	    // belgium
    213,	// аlgeria
    61,	    // australia
    47,	    // norway
    375,	// belorussia
    351,	// portugal
    992,	// tajikistan
    93,	    // afghanistan
    353,	// ireland
    358,	// finland
    39,	    // italy
])
